server:
  port: 8088
  
spring:
  application:
    name: dubbo-demo-provider
dubbo:
  scan:
    base-packages: io.kimmking.dubbo.demo.provider
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
